---
- name: Create new Fedora Vagrant Box
  hosts: localhost
  vars_files:
    - "playbook_vars.yml"
  tasks:
    - name: Create metadata file
      copy:
        src: "{{ playbook_dir }}/metadata.json.template"
        dest: "{{ playbook_dir }}/metadata.json"
    - name: Configure metadata file OS name
      replace:
        path: "{{ playbook_dir }}/metadata.json"
        regexp: 'OS_NAME'
        replace: "{{ os_name }}"
    - name: Configure metadata file OS version
      replace:
        path: "{{ playbook_dir }}/metadata.json"
        regexp: 'OS_VERSION'
        replace: "{{ os_version }}"
    - name: Configure metadata file arch
      replace:
        path: "{{ playbook_dir }}/metadata.json"
        regexp: 'ARCH'
        replace: "{{ arch }}"
    - name: Create Vagrant file
      copy:
        src: "{{ playbook_dir }}/Vagrantfile.template"
        dest: "{{ playbook_dir }}/Vagrantfile"
    - name: Configure Vagrant OS Name
      replace:
        path: "{{ playbook_dir }}/Vagrantfile"
        regexp: 'OS_NAME'
        replace: "{{ os_name }}"
    - name: Configure Vagrant OS Version
      replace:
        path: "{{ playbook_dir }}/Vagrantfile"
        regexp: 'OS_VERSION'
        replace: "{{ os_version }}"
    - name: Configure Architecture
      replace:
        path: "{{ playbook_dir }}/Vagrantfile"
        regexp: 'ARCH'
        replace: "{{ arch }}"
    - name: Copy template VM
      copy:
        src: "{{ parallels_path }}/{{ parallels_os_name }}.pvm"
        dest: "{{ playbook_dir }}"
    - name: Remove unnecessary files from source
      file:
        path: "{{ playbook_dir }}/{{ parallels_os_name }}.pvm/config.pvs.backup"
        state: absent
    - name: Optimize HDD
      command: "prl_disk_tool compact --hdd '{{ playbook_dir }}/{{ parallels_os_name }}.pvm/{{ parallels_hd_name }}.hdd'"
    - name: Package VM
      community.general.archive:
        path:
          - "{{ playbook_dir }}/{{ parallels_os_name }}.pvm"
          - "{{ playbook_dir }}/Vagrantfile"
          - "{{ playbook_dir }}/metadata.json"
        dest: "{{ playbook_dir }}/{{ parallels_os_name }}.box"
    - name: Add new box locally
      command: "vagrant box add --name {{ vagrant_account_name }}/{{ os_name }}-{{ os_version }}-{{ arch }} -c -f --machine-readable --provider parallels '{{ playbook_dir }}/{{ parallels_os_name }}.box'"
    - name: Upload box to Vagrant Cloud
      command: "vagrant cloud publish {{ vagrant_account_name }}/{{ os_name }}-{{ os_version }}-{{ arch }} -f -r {{ box_version}} parallels '{{ playbook_dir }}/{{ parallels_os_name }}.box'"
      when: publish_to_vagrant_cloud
    - name: Remove box file
      file:
        path: "{{ playbook_dir }}/{{ parallels_os_name }}.box"
        state: absent
      when: delete_box
    - name: Remove copied VM
      file:
        path: "{{ playbook_dir }}/{{ parallels_os_name }}.pvm"
        state: absent
    - name: Remove metadata file
      file:
        path: "{{ playbook_dir }}/metadata.json"
        state: absent
    - name: Remove Vagrant file
      file:
        path: "{{ playbook_dir }}/Vagrantfile"
        state: absent
